# Generated by Django 5.0.8 on 2024-08-13 23:10

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(db_index=True, max_length=128)),
                ('plan_description', models.CharField(blank=True, max_length=512)),
                ('grace_period', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='auth.group')),
            ],
            options={
                'ordering': ('plan_name',),
            },
        ),
        migrations.CreateModel(
            name='PlanCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=128, null=True, unique=True)),
                ('recurrence_period', models.PositiveSmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('recurrence_unit', models.CharField(blank=True, choices=[('0', 'once'), ('1', 'second'), ('2', 'minute'), ('3', 'hour'), ('4', 'day'), ('5', 'week'), ('6', 'month'), ('7', 'year')], default='6', max_length=1)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('billing_type', models.IntegerField(choices=[(0, 'Time Based'), (1, 'Usage Based')])),
                ('units_included', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('api_limit', models.PositiveIntegerField(default=0, help_text='API requests limit')),
                ('report_limit', models.PositiveIntegerField(default=0, help_text='Report generation limit')),
                ('currency', models.IntegerField(choices=[(0, 'USD'), (1, 'EUR'), (2, 'GBP'), (3, 'NGN')], default=3)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ('recurrence_unit', 'recurrence_period', 'cost'),
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_billing_start', models.DateTimeField(blank=True, null=True)),
                ('date_billing_end', models.DateTimeField(blank=True, null=True)),
                ('date_billing_last', models.DateTimeField(blank=True, null=True)),
                ('date_billing_next', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('units_remaining', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.plancost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user', 'date_billing_start'),
            },
        ),
        migrations.CreateModel(
            name='UsageTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usage_type', models.IntegerField(choices=[(0, 'API Request'), (1, 'Report Generation')])),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_tracker', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_tracker', to='subscriptions.usersubscription')),
            ],
            options={
                'unique_together': {('user', 'subscription', 'usage_type')},
            },
        ),
    ]
